# @package _global_

defaults:
  - override /checkpoint: pretrained
  - override /transformations: mae_adapted

trainer:
  max_epochs: 0

evaluator:
  max_epochs: 1

pl_module_eval:
  _target_: model.module_knn.ViTMAE_knn
  evaluated_epoch: ${evaluated_epoch}
  k:
    _target_: numpy.arange
    start: 2
    stop: 20

# overriding so that we get where we were if only just evaluating a run
logs_dir: ${base_logs_dir}/${checkpoint.run_path}
local_dir: ${base_outputs_dir}/${checkpoint.run_path}
evaluated_epoch: ${checkpoint.epoch}
