# @package _global_

base_logs_home: /cluster/scratch/abizeul/mae_alice
base_data_home: /cluster/scratch/abizeul

checkpoint_folders:
  vit-t:
    tinyimagenet:
      pixel:
        pixel:
          _75:
            _8: mae_tiny_pc_0.0_pixel_0.75/2024-08-27_19-14-36
        sampling:
          _None: 
            _8: mae_sampling_tiny/2024-09-24_08-25-21
      pc:
        pc:
          _20:
            _8: pcmae_tiny_pc_pc_pc_0.2_lossA/2024-12-05_23-10-16 
        sampling_pc:
          _None: 
            _8: pcmae_tiny_pcsampling_lossA/2024-12-08_16-34-35
    cifar10: 
      pixel:
        pixel:
          _75:
            _8: mae_cifar10_pc_pc_0.2/2025-02-10_10-57-45
        sampling:
          _None: 
            _8: mae_sampling_cifar10/2024-09-25_19-25-28
      pc:
        pc:
          _20:
            _8: pcmae_cifar10_pc_pc_pc_0.2/2025-02-10_11-41-15
        sampling_pc:
          _None: 
            _8: pcmae_cifar10_pcsampling_lossA/2024-12-08_10-35-07 
    bloodmnist:
      pixel:
        pixel:
          _75:
            _8: mae_blood_pc_0.0_pixel_0.75/2024-08-27_19-14-36
        sampling:
          _None: 
            _8: mae_sampling_blood/2024-09-23_19-22-33
      pc:
        pc:
          _20:
            _8: pcmae_blood_pc_pc_pc_0.2_lossA/2024-12-07_17-15-47 
        sampling_pc:
          _None: 
            _8: pcmae_blood_pcsampling_lossA/2024-12-08_16-34-35 
    dermamnist:
      pixel:
        pixel:
          _75:
            _8: mae_derma_pc_0.0_pixel_0.75/2024-08-27_19-14-57
        sampling:
          _None: 
            _8: mae_sampling_derma/2024-09-23_19-22-34
      pc:
        pc:
          _20:
            _8: pcmae_derma_pc_pc_pc_0.2_lossA/2024-12-06_04-00-36 
        sampling_pc:
          _None:
            _8: pcmae_derma_pcsampling_lossA/2024-12-08_10-35-07 
    pathmnist:
      pixel:
        pixel:
          _75:
            _8: mae_path_pc_0.0_pixel_0.75/2024-08-27_19-15-43
        sampling:
          _None: 
            _8: mae_sampling_path/2024-09-24_08-25-21
      pc:
        pc:
          _20:
            _8: pcmae_path_pc_pc_pc_0.2_lossA/2024-12-06_06-42-49 
        sampling_pc:
          _None: 
            _8: pcmae_path_pcsampling_lossA/2024-12-08_16-34-35 
