# @package _global_

transformation:
  train:
    _target_: torchvision.transforms.Compose
    transforms: ${compose_train_transforms}
  val:
    _target_: torchvision.transforms.Compose
    transforms: ${compose_val_transforms}

transformation_train_list:
  flip:
    _target_: torchvision.transforms.RandomHorizontalFlip
  tensor:
    _target_: torchvision.transforms.ToTensor
  normalize: 
    _target_: utils.Normalize
    mean: ${data.mean}
    std: ${data.std}
    
transformation_val_list:
  tensor:
    _target_: torchvision.transforms.ToTensor
  normalize: 
    _target_: utils.Normalize
    mean: ${data.mean}
    std: ${data.std}

compose_train_transforms:
  - ${transformation_train_list.flip}
  - ${transformation_train_list.tensor}
  - ${transformation_train_list.normalize}

compose_val_transforms:
  - ${transformation_val_list.tensor}
  - ${transformation_val_list.normalize}