# @package _global_

data:
  name: bloodmnist
  resolution: 64
  height: ${data.resolution}
  width: ${data.resolution}
  channels: 3
  batch_size: 512
  patch_size: 8
  eval_fn: 
    _target_: torch.nn.CrossEntropyLoss
    reduction: mean
  eval_logit_fn:
    _target_: torch.nn.Softmax
    dim: -1
  eval_type: multiclass
  str_patch_size: ${convert_str:${data.patch_size}}
  mean: 
    _target_: torch.tensor
    data: 
      _target_: numpy.load
      file: ${datasets.train.root}/bloodmnist_mean_reshaped.npy
  std: 
    _target_: torch.tensor
    data: 
      _target_: numpy.load
      file: ${datasets.train.root}/bloodmnist_std_reshaped.npy
  classes: 8
  task: 1

datasets:
  train:
    _target_: medmnist.BloodMNIST
    root: ${base_data_home}/medmnist
    split: train
    download: ${download}
    size: ${data.resolution}
    transform: ${transformation.train}

  val:
    _target_: medmnist.BloodMNIST
    root: ${base_data_home}/medmnist
    split: val
    download: ${download}
    size: ${data.resolution}
    transform: ${transformation.train}

  test:
    _target_: medmnist.BloodMNIST
    root: ${base_data_home}/medmnist
    split: val
    download: ${download}
    size: ${data.resolution}
    transform: ${transformation.train}

datamodule: 
  _target_: srd.dataloader.DataModule
  batch_size: ${data.batch_size}
  num_workers: 8
  classes: ${data.classes}
  channels: ${data.channels}
  resolution: ${data.resolution}
  name: ${data.name}

datamodule_eval:
  _target_: src.dataloader.DataModule
  batch_size: ${data.batch_size}
  num_workers: ${datamodule.num_workers}
  classes: ${data.classes}
  channels: ${data.channels}
  resolution: ${data.resolution}
  name: ${data.name}

extradata:
  pcamodule:
    _target_ : numpy.load
    file: ${base_data_home}/medmnist/bloodmnist_pc_matrix.npy

  eigenratiomodule:
    _target_: numpy.load
    file: ${base_data_home}/medmnist/bloodmnist_eigenvalues_ratio.npy

